# Site settings
title: Wyngate
description: > # this means to ignore newlines until "baseurl:"
  A mobile ad exchange for forward thinking apps, websites, and publishers.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://wyngate.com" # the base hostname & protocol for your site
# Build settings
markdown: redcarpet
