# Site settings
title: Wyngate
description: Disrupting residential development with unique, green-tech based housing solutions.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://wyngate.com" # the base hostname & protocol for your site
# Build settings
markdown: redcarpet
